export const POST_LOADING = "POST_LOADING";
export const POST_LOAD_ERROR = "POST_LOAD_ERROR";
export const POST_LOADED = "POST_LOADED";

export const REPORT_SUBMISSION_LOADING = "REPORT_SUBMISSION_LOADING";
export const REPORT_SUBMISSION_ERROR = "REPORT_SUBMISSION_ERROR";
export const REPORT_SUBMITTED = "REPORT_SUBMITTED";

export const POST_DETAIL_LOADING = "POST_DETAIL_LOADING";
export const POST_DETAIL_LOADED = "POST_DETAIL_LOADED";
export const POST_DETAIL_LOAD_ERROR = "POST_DETAIL_LOAD_ERROR";
