# Generated by Django 3.1 on 2021-07-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_post', '0002_post_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('description', models.TextField()),
                ('replied', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
